apiVersion: v1
kind: Service
metadata:
  name: virtual-vacation-backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8080
      name: http
  selector:
    app: virtual-vacation-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-vacation-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-vacation-backend
  template:
    metadata:
      labels:
        app: virtual-vacation-backend
    spec:
      initContainers:
        - name: wait-postgres
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z virtual-vacation-postgres 5432; do sleep 2; done"]
        - name: wait-redis
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z virtual-vacation-redis 6379; do sleep 2; done"]
      containers:
        - name: backend
          image: {{ .Values.image.backend }}
          env:
            - name: NODE_ENV
              value: {{ .Values.config.backend.nodeEnv | quote }}
            - name: PORT
              value: "8080"
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.config.postgres.user }}:{{ .Values.config.postgres.password }}@virtual-vacation-postgres:5432/{{ .Values.config.postgres.db }}?sslmode=disable"
            - name: REDIS_URL
              value: "redis://virtual-vacation-redis:6379/{{ .Values.config.redis.db }}"
          ports:
            - containerPort: 8080
          resources: {{- toYaml .Values.resources.tiny | nindent 12 }}
