apiVersion: v1
kind: Service
metadata:
  name: virtual-vacation-redis
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: 6379
      name: redis
  selector:
    app: virtual-vacation-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-vacation-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-vacation-redis
  template:
    metadata:
      labels:
        app: virtual-vacation-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.image.redis }}
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          resources: {{- toYaml .Values.resources.tiny | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: virtual-vacation-redis
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtual-vacation-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size.redis }}
{{- end }}
