{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name | default (include "device-ingestion.fullname" .) }}
  labels:
    app.kubernetes.io/name: {{ include "device-ingestion.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.externalSecret.targetName | default (include "device-ingestion.fullname" .) }}
    creationPolicy: Owner
  data:
{{- range .Values.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
{{- if .property }}
        property: {{ .property }}
{{- end }}
{{- end }}
{{- end }}
