apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "device-ingestion.fullname" . }}-migration
  labels:
    app.kubernetes.io/name: {{ include "device-ingestion.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "device-ingestion.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: migration
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - alembic
          - upgrade
          - head
{{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | nindent 10 }}
{{- end }}
        env:
{{- range .Values.env }}
          - name: {{ .name }}
{{- if hasKey . "valueFrom" }}
            valueFrom:
{{ toYaml .valueFrom | nindent 14 }}
{{- else }}
            value: "{{ .value }}"
{{- end }}
{{- end }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
